### ISSUE TITLE
Decouple plotting routines from `SkyScanResult`

### ISSUE THREAD

**Issue by mlincett** [icecube/skyreader#22]
The plotting methods of `SkyScanResult` are fairly complicated and could benefit from some refactoring.

I think it would be sensible to decouple all the plotting stuff from `SkyScanResult` and collect those in a separate `SkyScanPlotter` class.

Let me know if you have anything against it @ric-evans and @tianluyuan 

I plan to move forward with this in #21

**Comment by tianluyuan** [comment]
Sounds good. I support this 👍

**Comment by ric-evans** [comment]
Good idea, we could also use some unit tests to make sure we don't delete something in the refactor

FWIW I run pylint locally which produces an error when files get beyond 1000 lines. some of pylint's errors are more like suggestions than steadfast rules, but I've found a majority of them helpful

**Comment by ric-evans** [comment]
I wrote a gist for this exact purpose https://gist.github.com/ric-evans/aa55b6d054ef1fae9464b992631aa90d It does require multiple commits to `main`, but that's unavoidable

**Comment by mlincett** [comment]
> I wrote a gist for this exact purpose https://gist.github.com/ric-evans/aa55b6d054ef1fae9464b992631aa90d It does require multiple commits to `main`, but that's unavoidable
> 
> Note: You'll have to manually stop the CI to avoid an auto-release

@ric-evans would you mind doing this for me to duplicate `results.py`?

**Comment by ric-evans** [comment]
> > I wrote a gist for this exact purpose [gist.github.com/ric-evans/aa55b6d054ef1fae9464b992631aa90d](https://gist.github.com/ric-evans/aa55b6d054ef1fae9464b992631aa90d) It does require multiple commits to `main`, but that's unavoidable
> > Note: You'll have to manually stop the CI to avoid an auto-release
> 
> @ric-evans would you mind doing this for me to duplicate `results.py`?

Sure thing -- I'll leave the actual trimming to you. I'll put it on my list for tomorrow

**Comment by ric-evans** [comment]
@mlincett done. Check out https://github.com/icecube/skyreader/blob/main/skyreader/plot/plot.py, it has duplicate line history (blame) as `result.py`. You'll now need to remove what you don't want to keep from each file and fix the imports

**Comment by mlincett** [comment]
Fixed in #28
